version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: wednesday
  open-pull-requests-limit: 15
  target-branch: dev
  ignore:
  - dependency-name: react
    versions:
    - ">= 0"
  - dependency-name: react-dom
    versions:
    - ">= 0"
